spring:
  application:
    main:
      banner-mode: off
    cache:
      type: simple
server:
  port: 8080
# Compare this snippet from src/main/resources/application.yml:
weather-config:
  apiKey: https://api.openweathermap.org/data/2.5/weather?zip=